version: "3.3"

services:
  traefik:
    image: traefik:v2.2
    command:
      - --api.insecure
      - --providers.docker
      - --entrypoints.web.address=:80
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  api:
    image: node:12-stretch
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    command: sh -c "npm install && npm run dev"
    labels:
      - traefik.http.routers.api.rule=Host(`api.localhost`)
      - traefik.http.services.api.loadbalancer.server.port=3000
